#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 lumduan and matsurvey contributors
"""Build the guard's hash lists from plaintext sources kept outside the repository.

Plaintext never enters the repository.  This script reads the operator's local
term, fingerprint and file lists plus a local text corpus, and writes only
salted hashes into ``guard/``.  It refuses to read any source that lives inside
the repository, and it reports counts rather than content.

Each line of the term list becomes exactly one n-gram.  A line is normalised
with the guard's own tokenizer first, so spacing, case and punctuation variants
of a phrase are all covered by a single line.  A line that normalises to more
than the guard's maximum n-gram length could never match and is refused.
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from content_guard import (  # noqa: E402
    MAX_NGRAM,
    SALT,
    SHINGLE_HASH_LEN,
    SHINGLE_WORDS,
    GuardError,
    hex_tokens,
    number_tokens,
    salted,
    word_sequence,
)

HEADER = "# generated by scripts/build_denylist.py -- hashes only\n"
_SHA256_RE = re.compile(r"\A[0-9a-f]{64}\Z")


def read_lines(path: Path) -> list[tuple[int, str]]:
    if not path.exists():
        raise GuardError(f"missing input: {path}")
    out: list[tuple[int, str]] = []
    for number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        stripped = line.strip()
        if stripped and not stripped.startswith("#"):
            out.append((number, stripped))
    return out


def assert_outside(path: Path, repo_root: Path) -> None:
    resolved = path.resolve()
    if resolved == repo_root or repo_root in resolved.parents:
        raise GuardError(f"refusing to read plaintext from inside the repository: {resolved}")


def build_terms(path: Path, salt: str) -> set[str]:
    digests: set[str] = set()
    for number, line in read_lines(path):
        words = word_sequence(line)
        if not words:
            raise GuardError(f"{path}:{number}: line has no word tokens")
        if len(words) > MAX_NGRAM:
            raise GuardError(
                f"{path}:{number}: normalises to {len(words)} words; the guard only "
                f"matches windows of up to {MAX_NGRAM}, so this line could never match"
            )
        digests.add("term:" + salted("term", " ".join(words), salt))
    return digests


def build_fingerprints(path: Path, salt: str) -> tuple[set[str], int, int]:
    digests: set[str] = set()
    nums = hexes = 0
    for number, line in read_lines(path):
        kind, separator, value = line.partition(":")
        if not separator or kind not in {"num", "hex"}:
            raise GuardError(f"{path}:{number}: expected a 'num:' or 'hex:' prefix")
        value = value.strip()
        tokens = number_tokens(value) if kind == "num" else hex_tokens(value)
        if len(tokens) != 1 or tokens[0].length != len(value.lstrip("#")):
            raise GuardError(f"{path}:{number}: not a single well-formed {kind} token")
        digests.add(f"{kind}:" + salted(kind, tokens[0].value, salt))
        if kind == "num":
            nums += 1
        else:
            hexes += 1
    return digests, nums, hexes


def build_files(path: Path, salt: str) -> set[str]:
    digests: set[str] = set()
    for number, line in read_lines(path):
        candidate = line.split()[0].lower()
        if not _SHA256_RE.match(candidate):
            raise GuardError(f"{path}:{number}: expected a sha256 hex digest")
        digests.add("file:" + salted("file", candidate, salt))
    return digests


def build_shingles(corpus: Path, salt: str) -> tuple[set[str], list[tuple[str, int]]]:
    digests: set[str] = set()
    per_source: list[tuple[str, int]] = []
    if not corpus.is_dir():
        return digests, per_source
    for source in sorted(corpus.glob("*.txt")):
        words = word_sequence(source.read_text(encoding="utf-8", errors="replace"))
        per_source.append((source.name, len(words)))
        for index in range(len(words) - SHINGLE_WORDS + 1):
            window = " ".join(words[index : index + SHINGLE_WORDS])
            digests.add(salted("shingle", window, salt)[:SHINGLE_HASH_LEN])
    return digests, per_source


def write_list(path: Path, entries: set[str]) -> None:
    path.write_text(HEADER + "".join(f"{entry}\n" for entry in sorted(entries)), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    config_home = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config"))
    default_config = config_home / "matsurvey"
    default_local = Path(os.environ.get("MATSURVEY_LOCAL", Path.home() / "matsurvey-local"))
    repo_root = Path(__file__).resolve().parent.parent

    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--terms", type=Path, default=default_config / "terms.txt")
    parser.add_argument("--fingerprints", type=Path, default=default_config / "fingerprints.txt")
    parser.add_argument("--files", type=Path, default=default_config / "files.txt")
    parser.add_argument("--corpus", type=Path, default=default_local / "corpus")
    parser.add_argument("--out", type=Path, default=repo_root / "guard")
    parser.add_argument("--salt", default=SALT, help=argparse.SUPPRESS)
    args = parser.parse_args(argv)

    try:
        for source in (args.terms, args.fingerprints, args.files, args.corpus):
            assert_outside(source, repo_root)

        terms = build_terms(args.terms, args.salt)
        fingerprints, nums, hexes = build_fingerprints(args.fingerprints, args.salt)
        files = build_files(args.files, args.salt)
        shingles, per_source = build_shingles(args.corpus, args.salt)

        args.out.mkdir(parents=True, exist_ok=True)
        write_list(args.out / "denylist.v1.txt", terms | fingerprints | files)
        write_list(args.out / "shingles.v1.txt", shingles)
    except GuardError as exc:
        print(f"build-denylist: error: {exc}", file=sys.stderr)
        return 2

    print("build-denylist: counts only, no content is reported")
    print(f"  terms      {len(terms)}")
    print(f"  numbers    {nums}")
    print(f"  hex values {hexes}")
    print(f"  files      {len(files)}")
    print(f"  shingles   {len(shingles)}")
    for name, words in per_source:
        print(f"  corpus {name}: {words} words")
    if not per_source:
        print("  corpus: no sources present")
    return 0


if __name__ == "__main__":
    sys.exit(main())
